data_prep:
  version: "4.0"
  dataset_name: "bank_marketing_campaign_multi_algorithm_ensemble"
  target_column: "target"
  categorical_columns: ["V2", "V3", "V4", "V5", "V7", "V8", "V9", "V11", "V16"]
  numerical_columns: ["V1", "V6", "V10", "V12", "V13", "V14", "V15"]
  v14_missing_threshold: -1.0
  v6_outlier_bounds:
    lower: -1000
    upper: 10000

feature_prep:
  encoding_method: "label_encoder"
  drop_first: false
  handle_unknown: "ignore"
  binary_features:
    - "balance_positive"
    - "duration_high"

model_evaluation:
  cv_folds: 3
  primary_metric: "roc_auc"
  random_state: 42
  threshold_optimization: false
  threshold_metric: "roc_auc"
  thresholds_to_evaluate: [0.5]

model:
  model_type: "multi_algorithm_ensemble"
  model_params:
    base_algorithms:
      - algorithm: "gradient_boosting"
        params:
          n_estimators: 100
          learning_rate: 0.1
          max_depth: 6
          random_state: 42
      - algorithm: "xgboost"
        params:
          n_estimators: 100
          learning_rate: 0.1
          max_depth: 6
          random_state: 42
      - algorithm: "lightgbm"
        params:
          n_estimators: 100
          learning_rate: 0.1
          max_depth: 6
          random_state: 42
    ensemble_method: "voting"
    voting_type: "soft"
    calibration_enabled: true
    calibration_method: "sigmoid"
    calibration_cv: 3
  hyperparameter_tuning:
    enabled: false
  baseline_model:
    model_type: "gradient_boosting"
    params:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 6
      random_state: 42



